apiVersion: apps/v1
kind: Deployment
metadata:
  name: powersync
  namespace: powersync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: powersync
  template:
    metadata:
      labels:
        app: powersync
    spec:
      containers:
      - name: powersync
        image: journeyapps/powersync-service
        ports:
        - containerPort: 3000
        # env:
        # - name: DATABASE_URL
        #   value: "postgres://user:password@db.host:5432/dbname"
        # - name: JWT_SECRET
        #   value: "your_jwt_secret"
        # - name: POWERSYNC_PORT
        #   value: "3000"


---


apiVersion: v1
kind: Service
metadata:
  name: powersync
  namespace: powersync
spec:
  selector:
    app: powersync
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000


---


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: powersync-ingress
  namespace: powersync
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: powersync.ydeyeq.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: powersync
            port:
              number: 80